QDENGINE: Fix qdInventoryCellSet::put_object() build error on OpenBSD
This is meant to return a bool; the NULL used there triggers a build error
on (at least) OpenBSD/7.5 with default clang++:

error: cannot initialize return object of type 'bool' with an rvalue of type 'std::nullptr_t'
                return NULL;
                       ^~~~
/usr/include/sys/_null.h:12:14: note: expanded from macro 'NULL'
                ^~~~~~~

Introduced in commit d9de39b8c2d16096f9b5d74feeb0c9474f7d6627.